import { useEffect, useMemo, useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Save } from 'lucide-react'
import { calculateAdditionalChargeWithUnits } from '../domain/charge'
import { paAbsoluteToVacuum, vacuumToPaAbsolute } from '../domain/units'
import { type LengthUnit, type MassUnit } from '../domain/technical-conversions'
import { Notice, PageTitle, createMeasurementDraft, formatNumber, parseRequiredNumber } from './shared'

const massUnits: MassUnit[] = ['g', 'kg', 'lb', 'oz']
const lengthUnits: LengthUnit[] = ['m', 'ft']

export function ChargePage() {
  const navigate=useNavigate(),[factory,setFactory]=useState('0,85'),[fu,setFu]=useState<MassUnit>('kg'),[included,setIncluded]=useState('5'),[installed,setInstalled]=useState('12'),[lu,setLu]=useState<LengthUnit>('m'),[gpm,setGpm]=useState('20'),[recovered,setRecovered]=useState('0'),[added,setAdded]=useState('0'),[mu,setMu]=useState<MassUnit>('g'),[saved,setSaved]=useState(false)
  const calc=useMemo(()=>{try{return{value:calculateAdditionalChargeWithUnits({factoryCharge:parseRequiredNumber(factory,'carga'),factoryUnit:fu,includedLength:parseRequiredNumber(included,'longitud'),installedLength:parseRequiredNumber(installed,'longitud'),lengthUnit:lu,additionalPerMeterG:parseRequiredNumber(gpm,'g/m'),recovered:parseRequiredNumber(recovered,'recuperado'),recoveredUnit:mu,added:parseRequiredNumber(added,'añadido'),addedUnit:mu}),error:''}}catch(e){return{value:null,error:e instanceof Error?e.message:'Datos no válidos'}}},[factory,fu,included,installed,lu,gpm,recovered,added,mu])
  const save=async()=>{if(!calc.value)return;await createMeasurementDraft({workType:'Cálculo de carga adicional',recoveredRefrigerant:`${calc.value.recoveredG} g`,addedRefrigerant:`${calc.value.addedG} g`,observations:`Carga total orientativa ${formatNumber(calc.value.totalChargeG/1000,3)} kg; adicional ${formatNumber(calc.value.additionalChargeG,0)} g.`});setSaved(true)}
  return <main className="sz-screen"><PageTitle eyebrow="Carga por peso" title="Calculadora de carga" description="Usa exclusivamente el dato g/m del fabricante."/><section className="sz-panel sz-form"><div className="sz-two-columns"><label>Carga placa<input value={factory} onChange={e=>setFactory(e.target.value)}/></label><label>Unidad<select value={fu} onChange={e=>setFu(e.target.value as MassUnit)}>{massUnits.map(u=><option key={u}>{u}</option>)}</select></label></div><div className="sz-two-columns"><label>Longitud incluida<input value={included} onChange={e=>setIncluded(e.target.value)}/></label><label>Longitud instalada<input value={installed} onChange={e=>setInstalled(e.target.value)}/></label></div><label>Unidad longitud<select value={lu} onChange={e=>setLu(e.target.value as LengthUnit)}>{lengthUnits.map(u=><option key={u}>{u}</option>)}</select></label><label>Carga adicional g/m<input value={gpm} onChange={e=>setGpm(e.target.value)}/></label><div className="sz-two-columns"><label>Recuperado<input value={recovered} onChange={e=>setRecovered(e.target.value)}/></label><label>Añadido<input value={added} onChange={e=>setAdded(e.target.value)}/></label></div><label>Unidad<select value={mu} onChange={e=>setMu(e.target.value as MassUnit)}>{massUnits.map(u=><option key={u}>{u}</option>)}</select></label></section>{calc.error?<Notice tone="danger"><p>{calc.error}</p></Notice>:calc.value&&<section className="sz-result"><small>Carga total orientativa</small><strong>{formatNumber(calc.value.totalChargeG/1000,3)} kg</strong><div className="sz-data-list"><p><span>Longitud adicional</span><strong>{formatNumber(calc.value.additionalLengthM,1)} m</strong></p><p><span>Carga adicional</span><strong>{formatNumber(calc.value.additionalChargeG,0)} g</strong></p><p><span>Recuperado / añadido</span><strong>{formatNumber(calc.value.recoveredG,0)} / {formatNumber(calc.value.addedG,0)} g</strong></p></div><div className="sz-button-row"><button className="sz-button secondary" type="button" onClick={save}><Save/>Guardar intervención</button><button className="sz-button ghost" type="button" onClick={()=>navigate('/interventions')}>Abrir trabajo</button></div>{saved&&<Notice tone="success"><p>Borrador guardado.</p></Notice>}</section>}<Notice tone="warning"><p>La presión por sí sola no determina la carga correcta.</p></Notice></main>
}

export function VacuumPage() {
  const [microns,setMicrons]=useState('500'),[initial,setInitial]=useState('2500'),[finalValue,setFinal]=useState('650'),[phase,setPhase]=useState<'process'|'isolation'|'stability'|'finished'>('process'),[seconds,setSeconds]=useState(0),[running,setRunning]=useState(false),[saved,setSaved]=useState(false)
  const timer=useRef<number|null>(null)
  useEffect(()=>{if(!running)return;timer.current=window.setInterval(()=>setSeconds(s=>s+1),1000);return()=>{if(timer.current)window.clearInterval(timer.current)}},[running])
  const value=Number(microns.replace(',','.')),pa=Number.isFinite(value)?vacuumToPaAbsolute(Math.max(0,value),'micron'):NaN,change=Number(finalValue.replace(',','.'))-Number(initial.replace(',','.')),elapsed=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`
  const save=async()=>{await createMeasurementDraft({workType:'Vacío y estabilidad',finalVacuum:`${microns} micrones`,vacuumTestDuration:elapsed,observations:`Fase ${phase}; inicial ${initial}; final ${finalValue}; variación ${change} μm.`});setSaved(true)}
  return <main className="sz-screen"><PageTitle eyebrow="Procedimiento" title="Vacío y estabilidad" description="Registra fases y evolución sin certificar automáticamente ausencia de fugas."/><section className="sz-panel sz-form"><div className="sz-segmented four">{([['process','Vacío'],['isolation','Aislar'],['stability','Estabilidad'],['finished','Fin']] as const).map(([v,l])=><button type="button" key={v} className={phase===v?'active':''} onClick={()=>setPhase(v)}>{l}</button>)}</div><label>Micrones actuales<input value={microns} onChange={e=>setMicrons(e.target.value)}/></label><div className="sz-two-columns"><label>Inicial μm<input value={initial} onChange={e=>setInitial(e.target.value)}/></label><label>Final μm<input value={finalValue} onChange={e=>setFinal(e.target.value)}/></label></div></section><section className="sz-result"><small>Fase: {phase}</small><strong>{Number.isFinite(value)?`${formatNumber(value,0)} μm`:'—'}</strong><div className="sz-timer">{elapsed}</div><div className="sz-button-row"><button className="sz-button primary" type="button" onClick={()=>setRunning(!running)}>{running?'Pausar':'Iniciar'}</button><button className="sz-button secondary" type="button" onClick={()=>{setRunning(false);setSeconds(0)}}>Reiniciar</button></div><div className="sz-data-list"><p><span>mbar abs</span><strong>{Number.isFinite(pa)?formatNumber(paAbsoluteToVacuum(pa,'mbar_abs'),4):'—'}</strong></p><p><span>Variación</span><strong>{Number.isFinite(change)?`${formatNumber(change,0)} μm`:'—'}</strong></p></div><button className="sz-button secondary full" type="button" onClick={save}><Save/>Guardar registro</button>{saved&&<Notice tone="success"><p>Registro guardado.</p></Notice>}</section><Notice tone="warning"><p>La subida de micrones puede deberse a humedad, desgasificación, temperatura, conexiones o fuga.</p></Notice></main>
}
