import { useState } from 'react'
import { Search, Stethoscope } from 'lucide-react'
import { refrigerantTables } from '../data/generated'
import { refrigerantCategoryLabels, refrigerantMetadata, type RefrigerantCategory } from '../data/refrigerant-metadata'
import { interpolatePressureFromTemperature } from '../domain/refrigerants/calculations'
import { formatRange, maxGlideK, tableStatusLabel } from '../domain/refrigerants/summary'
import { runDiagnosticRules } from '../domain/diagnostics/rules'
import { EmptyState, Notice, PageTitle, formatNumber, getTable, optionalNumber } from './shared'

export function RefrigerantsPage() {
  const [category, setCategory] = useState<RefrigerantCategory | 'all'>('all')
  const [query, setQuery] = useState('')
  const visible = refrigerantTables.filter((table) => {
    const meta = refrigerantMetadata[table.refrigerant]
    return (category === 'all' || meta.category === category) && `${meta.name} ${table.refrigerant}`.toLowerCase().includes(query.toLowerCase())
  })
  return <main className="sz-screen"><PageTitle eyebrow="Base técnica" title="Refrigerantes" description="Estado de tablas, seguridad y limitaciones visibles."/><section className="sz-panel sz-form"><label className="sz-search"><Search/><span className="sr-only">Buscar</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="R32, R410A, propano…"/></label><div className="sz-segmented three">{(['all','traditional','lower-gwp'] as const).map(value=><button type="button" key={value} className={category===value?'active':''} onClick={()=>setCategory(value)}>{refrigerantCategoryLabels[value]}</button>)}</div></section><Notice tone="warning"><strong>No son equivalencias directas.</strong><p>No sustituyas ni mezcles refrigerantes por similitud de presión o menor GWP.</p></Notice><div className="sz-refrigerant-grid">{visible.map(table=>{const meta=refrigerantMetadata[table.refrigerant],glide=maxGlideK(table);return <article className="sz-refrigerant-card" key={table.refrigerant}><div className="sz-card-head"><div><span className="sz-eyebrow">{refrigerantCategoryLabels[meta.category]}</span><h2>{meta.name}</h2></div><span className={`sz-badge ${table.generator==='CoolProp'?'ok':'pending'}`}>{table.generator==='CoolProp'?'P/T validada':'Pendiente'}</span></div><dl><dt>Tipo</dt><dd>{meta.familyType.value??table.refrigerantType}</dd><dt>Seguridad</dt><dd>{meta.safetyClass.value??meta.safetyClass.note}</dd><dt>GWP / PCA</dt><dd>{meta.gwp.value??meta.gwp.note}</dd><dt>Glide</dt><dd>{glide===null?'Pendiente':`${formatNumber(glide)} K`}</dd><dt>Rango</dt><dd>{formatRange(table)}</dd><dt>Aceite</dt><dd>{meta.oils.value??meta.oils.note}</dd><dt>Carga</dt><dd>{meta.chargingMethod.value??meta.chargingMethod.note}</dd></dl><ul className="sz-warning-list">{meta.warnings.slice(0,3).map(w=><li key={w}>{w}</li>)}</ul><small className="sz-source">Revisión: {meta.safetyClass.reviewedAt}. {table.limitations.join(' ')}</small></article>})}</div>{!visible.length&&<EmptyState icon={<Search/>} title="Sin resultados" text="No hay refrigerantes con ese filtro."/>}</main>
}

function pressure(tableName: string, temperature: number) {
  try { return interpolatePressureFromTemperature(getTable(tableName), temperature, 'dew') / 100000 } catch { return null }
}

export function ComparePage() {
  const [left,setLeft]=useState('R32'),[right,setRight]=useState('R410A')
  const rows=[-20,-10,0,10,20,30,40],leftTable=getTable(left),rightTable=getTable(right)
  return <main className="sz-screen"><PageTitle eyebrow="Comparación informativa" title="Comparador" description="Compara presión y metadatos sin declarar sustituciones."/><div className="sz-compare-select"><select value={left} onChange={e=>setLeft(e.target.value)}>{refrigerantTables.map(r=><option key={r.refrigerant}>{r.refrigerant}</option>)}</select><span>VS</span><select value={right} onChange={e=>setRight(e.target.value)}>{refrigerantTables.map(r=><option key={r.refrigerant}>{r.refrigerant}</option>)}</select></div><div className="sz-compare-cards">{[leftTable,rightTable].map(t=>{const m=refrigerantMetadata[t.refrigerant];return <article className="sz-panel" key={t.refrigerant}><h2>{t.refrigerant}</h2><div className="sz-data-list"><p><span>Estado</span><strong>{tableStatusLabel(t)}</strong></p><p><span>Seguridad</span><strong>{m.safetyClass.value??'Pendiente'}</strong></p><p><span>GWP</span><strong>{m.gwp.value??'Pendiente'}</strong></p><p><span>Glide</span><strong>{maxGlideK(t)?.toFixed(2)??'Pendiente'} K</strong></p></div></article>})}</div><div className="sz-table-wrap"><table><thead><tr><th>Temperatura</th><th>{left} bar(a)</th><th>{right} bar(a)</th></tr></thead><tbody>{rows.map(t=>{const a=pressure(left,t),b=pressure(right,t);return <tr key={t}><td>{t} °C</td><td>{a===null?'Fuera de rango':formatNumber(a)}</td><td>{b===null?'Fuera de rango':formatNumber(b)}</td></tr>})}</tbody></table></div><Notice tone="danger"><strong>No mezclar refrigerantes.</strong><p>Comprueba aceite, compresor, expansión, materiales, homologación, seguridad y fabricante.</p></Notice></main>
}

export function DiagnosticsPage() {
  const [mode,setMode]=useState<'frio'|'calor'>('frio'),[delta,setDelta]=useState('5'),[superheat,setSuperheat]=useState('16'),[subcooling,setSubcooling]=useState('2'),[ratio,setRatio]=useState(''),[observations,setObservations]=useState('')
  const findings=runDiagnosticRules({mode,thermalDeltaK:optionalNumber(delta),superheatK:optionalNumber(superheat),subcoolingK:optionalNumber(subcooling),pressureRatio:optionalNumber(ratio),observations})
  return <main className="sz-screen"><PageTitle eyebrow="Ayuda a la decisión" title="Diagnóstico guiado" description="Hipótesis y siguientes comprobaciones, nunca una orden automática de carga."/><section className="sz-panel sz-form"><label>Modo<select value={mode} onChange={e=>setMode(e.target.value as typeof mode)}><option value="frio">Frío</option><option value="calor">Bomba de calor</option></select></label><div className="sz-two-columns"><label>Salto térmico K<input value={delta} onChange={e=>setDelta(e.target.value)}/></label><label>Relación compresión<input value={ratio} onChange={e=>setRatio(e.target.value)} placeholder="Opcional"/></label></div><div className="sz-two-columns"><label>Recalentamiento K<input value={superheat} onChange={e=>setSuperheat(e.target.value)}/></label><label>Subenfriamiento K<input value={subcooling} onChange={e=>setSubcooling(e.target.value)}/></label></div><label>Observaciones<textarea value={observations} onChange={e=>setObservations(e.target.value)} placeholder="Filtros, hielo, ventiladores, ambiente…"/></label></section><Notice tone="warning"><p>Interpreta conjuntamente presiones, temperaturas, caudal, expansión y fabricante.</p></Notice><div className="sz-findings">{findings.map((f,i)=><article className="sz-finding" key={`${f.cause}-${i}`}><div className="sz-card-head"><h2>{f.cause}</h2><span className={`sz-badge confidence-${f.confidence}`}>Confianza {f.confidence}</span></div><h3>Datos compatibles</h3><ul>{f.supportingData.map(x=><li key={x}>{x}</li>)}</ul><h3>Comprobaciones</h3><ol>{f.checks.map(x=><li key={x}>{x}</li>)}</ol>{f.limitations.length>0&&<div className="sz-limitations">{f.limitations.map(x=><p key={x}>{x}</p>)}</div>}</article>)}</div>{!findings.length&&<EmptyState icon={<Stethoscope/>} title="Sin hipótesis coincidentes" text="No confirma que el equipo esté correcto; pueden faltar mediciones."/>}</main>
}
