import { Activity, ArrowUpDown, Cable, Fan, Flame, Gauge, Home, LockKeyhole, Scale, Snowflake, Stethoscope, Table2, Thermometer, Waves, Wind, Zap } from 'lucide-react'

export type ToolCategory = 'refrigerantes' | 'climatizacion' | 'conductos' | 'aerotermia' | 'electricidad' | 'diagnostico'
export type ToolStatus = 'active' | 'planned'

export const toolCategories: Array<{ id: 'todos' | ToolCategory; label: string }> = [
  { id: 'todos', label: 'Todos' },
  { id: 'refrigerantes', label: 'Refrigerantes' },
  { id: 'climatizacion', label: 'Climatización' },
  { id: 'conductos', label: 'Conductos' },
  { id: 'aerotermia', label: 'Aerotermia / Hidráulica' },
  { id: 'electricidad', label: 'Electricidad' },
  { id: 'diagnostico', label: 'Diagnóstico' },
]

export const tools = [
  {
    id: 'pt',
    title: 'Regla P/T',
    subtitle: 'Presión y temperatura con burbuja, rocío y glide.',
    path: '/pt',
    icon: Thermometer,
    category: 'refrigerantes',
    status: 'active',
  },
  {
    id: 'superheat',
    title: 'Recalentamiento',
    subtitle: 'Presión de aspiración, saturación y temperatura de tubería.',
    path: '/superheat',
    icon: ArrowUpDown,
    category: 'refrigerantes',
    status: 'active',
  },
  {
    id: 'subcooling',
    title: 'Subenfriamiento',
    subtitle: 'Presión de líquido, saturación y temperatura real.',
    path: '/subcooling',
    icon: Snowflake,
    category: 'refrigerantes',
    status: 'active',
  },
  {
    id: 'vacuum',
    title: 'Vacío y estanqueidad',
    subtitle: 'Micrones, estabilidad, tiempos y advertencias de procedimiento.',
    path: '/vacuum',
    icon: Gauge,
    category: 'refrigerantes',
    status: 'active',
  },
  {
    id: 'charge',
    title: 'Carga adicional',
    subtitle: 'Carga por longitud usando placa y dato del fabricante.',
    path: '/charge',
    icon: LockKeyhole,
    category: 'refrigerantes',
    status: 'active',
  },
  {
    id: 'converter',
    title: 'Conversor técnico',
    subtitle: 'Presión, vacío, temperatura, potencia, masa y caudal.',
    path: '/converter',
    icon: Gauge,
    category: 'electricidad',
    status: 'active',
  },
  {
    id: 'refrigerants',
    title: 'Fichas de refrigerantes',
    subtitle: 'Seguridad, GWP, glide, aceites, carga y fuentes.',
    path: '/refrigerants',
    icon: Table2,
    category: 'refrigerantes',
    status: 'active',
  },
  {
    id: 'compare',
    title: 'Comparador',
    subtitle: 'Comparación orientativa sin declarar sustitución directa.',
    path: '/compare',
    icon: Scale,
    category: 'refrigerantes',
    status: 'active',
  },
  {
    id: 'diagnostics',
    title: 'Diagnóstico guiado',
    subtitle: 'Hipótesis, confianza, datos que faltan y comprobaciones.',
    path: '/diagnostics',
    icon: Stethoscope,
    category: 'diagnostico',
    status: 'active',
  },
  {
    id: 'psychrometrics',
    title: 'Psicrometría',
    subtitle: 'Temperatura seca, humedad, punto de rocío y entalpía.',
    path: '/psychrometrics',
    icon: Waves,
    category: 'climatizacion',
    status: 'active',
  },
  {
    id: 'thermal-load',
    title: 'Carga térmica y frigorías',
    subtitle: 'Transmisión, radiación, humedad, sensible, latente y potencia de diseño.',
    path: '/thermal-load',
    icon: Flame,
    category: 'climatizacion',
    status: 'active',
  },
  {
    id: 'ducts',
    title: 'Caudales y conductos',
    subtitle: 'Caudal, velocidad, sección, diámetro equivalente y equilibrado.',
    path: '/ducts',
    icon: Wind,
    category: 'conductos',
    status: 'active',
  },
  {
    id: 'pressure-loss',
    title: 'Pérdidas de carga',
    subtitle: 'Tramos, accesorios, rugosidad y pérdida total.',
    path: '/planned/pressure-loss',
    icon: Activity,
    category: 'conductos',
    status: 'planned',
  },
  {
    id: 'aerothermal-sizing',
    title: 'Dimensionado de aerotermia',
    subtitle: 'Carga, equipo, modulación, ACS, hidráulica, electricidad y coste.',
    path: '/aerothermal-sizing',
    icon: Home,
    category: 'aerotermia',
    status: 'active',
  },
  {
    id: 'hydraulics',
    title: 'Caudal de agua',
    subtitle: 'Caudal hidráulico desde potencia térmica y salto de temperatura.',
    path: '/hydraulics',
    icon: Fan,
    category: 'aerotermia',
    status: 'active',
  },
  {
    id: 'electrical',
    title: 'Electricidad asociada',
    subtitle: 'Intensidad, protecciones, caída de tensión y motores.',
    path: '/planned/electrical',
    icon: Zap,
    category: 'electricidad',
    status: 'planned',
  },
  {
    id: 'uta-fancoils',
    title: 'UTA, fan coils e inductores',
    subtitle: 'Caudal, baterías, recuperación, potencia y condensación.',
    path: '/planned/uta-fancoils',
    icon: Cable,
    category: 'climatizacion',
    status: 'planned',
  },
] as const
